name: manual actions trigger - workflow_dispacth
run-name: Deploy by @${{ github.actor }}
on:
   workflow_dispatch:
     inputs:
       loglevel:
         description: 'Log Level'
         type: string
         required: true
         default: 'warning'

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - run: | 
         echo "Log Level: ${{ github.event.inputs.loglevel }}"
