name: second_workflow
run-name: Triggered by @${{ github.actor}}
on:
  workflow_run:
    workflows: 
      - 'first_workflow'
    types:
      - 'completed'
jobs:
  second_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying the project"
