name: first_workflow
run-name: triggered by @${{ github.actor }}
on:
  push:
     branches: 
       - 'main'
jobs:
  first_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Build
      run: echo "Building the project"
