name: "temp.yaml"
on: 
  push:
    branches:
      - main

jobs:
  githubcontext: 
    runs-on: ubuntu-latest
    steps:
      - name: "github-context"
        id: "github-context"
        run: |
          echo "   action: ${{ github.action }}"
          echo "    actor: ${{ github.actor }}"
          echo "      env: ${{ github.env }}"
          echo "    event: ${{ github.event_name }}"
          echo "workspace: ${{ github.workspace }}"
          
         
        
