name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  Learn:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello $NAME, you are $SEX and $AGE years old"
      
