name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: step1
        id: step1
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
      - name: step2
        id: step2
        run: |
          echo "test=world" >> $GITHUB_OUTPUT
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          out1: ${{ needs.job1.outputs.output1 }}
          out2: ${{ needs.job1.outputs.output2 }}
        run: |
          echo "$out1 $out2"
