name: Learn - Github actions
run-name: Triggered by @${{ github.user }}
on:
  push:
    branches:
      - 'main'

jobs:
  printValues:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.user }}"
