name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  Learn:
    runs-on: ubuntu-latest
    steps:
      - run: |
           mysql_user: ${{ vars.MYSQL_USER }}
           mysql_host: ${{ vars.MYSQL_HOST }}
           mysql_port: ${{ vars.MYSQL_PORT }}
