name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'

jobs:
  printValues:
    runs-on: ubuntu-latest
    steps:
      - id : print-github-actor
        run: echo "Hello ${{ github.actor }}"
      - id: print-github-action
        run: echo "Action ${{ github.action }}"
