name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  Learn:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ vars.NAME }}, you are ${{ vars.SEX }} and ${{ vars.AGE }} years old"
