name: "temp.yaml"
on: 
  push:
    branches:
      - main

jobs:
  githubcontext: 
    runs-on: ubuntu-latest
    steps:
      - id: "github-action"
        run: |
          echo "Hello Srinivas!"
          echo "${{ github }}"
          echo "Github-action: ${{ github.action }}"
      - id: "github-actor"
        run: |
          echo "${{ github.actor }}"
