name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build code and set the result.
        run: |
          #Build your project
          echo "BUILD_STATUS=success" >> $GITHUB_ENV
  
  unittest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the code based on the BUILD_STATUS
        run: |
          echo "env.$BUILD_STATUS"
