name: "temp.yaml"
on: 
  push:
    branches:
      - main

jobs:
  githubcontext: 
    runs-on: ubuntu-latest
    steps:
      - name: "github-action"
        id: "github-action"
        run: |
          echo "${{ github.action }}"
      - name: "github-actor"
        id: "github-actor"
        run: |
          echo "${{ github.actor }}"
      - name: "github-env"
        id: "github-env"
        run: |
          echo "${{ github.env }}"
         
        
