name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
env:
   NAME: 'Srinivas Antarvedi'
   AGE: '44'
   SEX: 'Male'

jobs:
  Learn:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello $NAME, you are $SEX and $AGE years old"
      - run: env
