name: "temp.yaml"
on: 
  push:
    branches:
      - main

jobs:
  githubcontext: 
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        id: "github-context"
        run: |
          echo "Hello Srinivas!"
          echo "${{ github }}"
          echo "Github-action: ${{ github.action }}"
        
