name: Learn - Github actions
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'

jobs:
  printValues:
    runs-on: ubuntu-latest
    steps:
      - id : print-github-actor
        run: echo "Action ${{ github.action }}"
      - id: print-github-action
        run: echo "Action ${{ github.action }}"
      - id: print-github-base_ref
        run: echo "base-ref ${{ github.base_ref }}"
      - id: print-event-name
        run: echo "eventname ${{ github.event_name }}"
      - id: print-event-path
        run: echo "eventpath ${{ github.event_path }}"
