name: learn-github-actions
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
#on:
#  push:
#    branches:
#      - 'main'

on:
   workflow_dispatch:
     inputs:
       loglevel:
         description: 'Log Level'
         type: string
         required: true
         default: 'warning'
         

jobs:
  welcome-to-ga:
    runs-on: ubuntu-latest
    steps:
      - run: | 
         echo "Log Level: ${{ github.events.inputs.loglevel }}"
 
