name: learn-github-actions
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  welcome-to-ga:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo Hello Srinivas Antarvedi
      - name: Print Whole github context
        run: echo ${{ github.action }}
