name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "Welcome... Srinivas"
      - name: GoodBye
        run: echo "GoodBye... Srinivas"
      - name: Using bash
        shell: bash
        run:  |
          echo "----------"
          # echo ""
          # dmidecode -t 1
          echo ""
          uname -a
          echo ""
          cat /etc/*release*
          echo ""
          echo "-----------"